language: php
php:
  - 5.5
  - 5.4
env:
  - TEST_SUITE=unit
  - TEST_SUITE=acceptance

matrix:
  include:
    - php: 5.5
      env: TEST_SUITE=cs

services:
  - elasticsearch
  - redis-server

install:
  - sudo apt-get install beanstalkd

before_script:
  - phpenv config-add tests/travis/php-custom.ini
  - cp tests/travis/config.local.neon app/config/config.local.neon
  - psql -c 'create database khanovaskola;' -U postgres
  - rm tests/acceptance.suite.yml
  - mv tests/travis/acceptance.suite.yml tests/acceptance.suite.yml
  - beanstalkd -l 127.0.0.1 -p 13000 &
  - bin/console db:migrate
  - bin/console db:fill
  - php -S localhost:8000 -t www/ &

script: sh tests/travis/test.sh

after_success:
  - sh tests/travis/success.sh
after_failure:
  - sh tests/travis/fail.sh
