language: php
php:
  - 5.5
  - 5.6
env:
  global:
    - secure: "jYIOGZdXOciJOVJVMXmvCf+AvxwBsVETYAQN/4dhpfuQVmJu2bbkwa5Q1tsMI7rbFqlhVFb+tmjXLBWi/IQgI0An8aUvEQ8lP8W3IuD+ADhtTAKzGgLvAeuhU1yUyRyAvLh6BpwUU5ksJpqrvR10av8nH8oo062zA092/DbrAA0=" # FB_SECRET
    - secure: "TvrlwT4oA61v7DGN59YNKXvNSuFpc5QmeJXtuT1r2sgKAKhBhTougK5VXV8EJj+WQUR7CZKAJA//wzfL+RzvxgEyT0IKIccEFck7w6pRAhAYgMXXezM81EoEs1CcKB/boPy+PquG5kEuGuA/Xa8KQ3g6Z7t5rPNO3e6wbolm8qI=" # GOOGLE_SECRET
    - secure: "NUqvXHx/GBvDrzVVNxL/7pJOWmOyYvww/PGHIJJhCpwzkVpw8zU9UgRpKEQKh7djXl3u1JqsveE8zt2gxwS90onRha//75pt2KOYhB5cpoTcsSZQE1tNRCgNoXErg1oUhhcVvOsUL+B9VxApNVXJOn+n/HEW3IAbfgQD48P73h4=" # GOOGLE_KEY
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=acceptance
    - TEST_SUITE=cs

services:
  - elasticsearch
  - redis-server

before_script: sh tests/travis/setup.sh
script: sh tests/travis/test.sh
after_success: sh tests/travis/success.sh
after_failure: sh tests/travis/fail.sh
