language: php
php:
  - 5.5
  - 5.4
env:
  - TEST_SUITE=unit
  - TEST_SUITE=acceptance

matrix:
  include:
    - php: 5.5
      env: TEST_SUITE=cs

services:
  - elasticsearch
  - redis-server

before_script: sh tests/travis/setup.sh
script: sh tests/travis/test.sh
after_success: sh tests/travis/success.sh
after_failure: sh tests/travis/fail.sh

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
