language: php
php:
  - 5.5
  - 5.4
env:
  - TEST_SUITE=unit
  - TEST_SUITE=acceptance

matrix:
  include:
    - php: 5.5
      env: TEST_SUITE=cs

services:
  - elasticsearch
  - redis-server

install:
  - sudo apt-get install beanstalkd

before_script:
  - cat tests/travis/php-custom.ini >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp tests/travis/config.local.neon app/config/config.local.neon
  - psql -c 'create database khanovaskola;' -U postgres
  - rm tests/acceptance.suite.yml
  - mv tests/travis/acceptance.suite.yml tests/acceptance.suite.yml
  - beanstalkd -l 127.0.0.1 -p 13000 &
  - php -S localhost:8000 -t www/ &
  - sleep 10 # wait for all services to load
  - bin/console db:migrate
  - bin/console es:recreate
  - bin/console db:fill --testdata

script: sh tests/travis/test.sh

after_success:
  - sh tests/travis/success.sh
after_failure:
  - sh tests/travis/fail.sh
