#!/usr/bin/env php
<?php

use App\Factories\LogFactory;
use App\Services\Queue;
use App\Tasks\Task;
use Monolog\Logger;
use Nette\DI\Container;

/** @var Container $container */
$container = require __DIR__ . '/../app/bootstrap.php';

/** @var Queue $queue */
$queue = $container->getService('queue');

/** @var Logger $log */
LogFactory::$name = LogFactory::WORKER;
$log = $container->getService('log');

while (TRUE)
{
	$queue->watch(function(Task $task, callable $next) use ($container, $queue, $log) {
		$class = get_class($task);
		$log->addInfo("Running task $class");
		try
		{
			if (!$task->run($container))
			{
				$log->addNotice("Task $class failed", ['task' => $task]);
			}
			$next();
		}
		catch (Exception $e)
		{
			$file = \Nette\Diagnostics\Debugger::log($e);
			$queue->buryTask($task);
			$name = get_class($e);
			$log->addWarning("Task $class throwed $name and has been burried", ['dump' => $file]);
		}
	});
}
