CREATE TABLE student_invites (
  id SERIAL NOT NULL,
  sender_id INT NOT NULL,
  student_id INT DEFAULT NULL,
  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
  email VARCHAR(255) NOT NULL,
  accepted BOOLEAN NOT NULL,
  PRIMARY KEY(id)
);

CREATE INDEX IDX_EE48DF94F624B39D ON student_invites (sender_id);

CREATE INDEX IDX_EE48DF94CB944F1A ON student_invites (student_id);

ALTER TABLE
  student_invites
ADD
  CONSTRAINT FK_EE48DF94F624B39D FOREIGN KEY (sender_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE
  student_invites
ADD
  CONSTRAINT FK_EE48DF94CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
