ALTER TABLE
  editors_x_subjects
ADD
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE
  editors_x_subjects
ADD
  CONSTRAINT fk_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE INITIALLY IMMEDIATE;


ALTER TABLE
  editors_x_schemas
ADD
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE
  editors_x_schemas
ADD
  CONSTRAINT fk_schema FOREIGN KEY (schema_id) REFERENCES schemas (id) NOT DEFERRABLE INITIALLY IMMEDIATE;


ALTER TABLE
  editors_x_blocks
ADD
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE
  editors_x_blocks
ADD
  CONSTRAINT fk_block FOREIGN KEY (block_id) REFERENCES blocks (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
