ALTER TABLE "public"."answers" DROP CONSTRAINT "fk_50d0c606a76ed395",
DROP CONSTRAINT "idx_50d0c60640e5ae12";
ALTER TABLE "public"."answers" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_content" FOREIGN KEY ("content_id") REFERENCES "public"."contents" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."comments" DROP CONSTRAINT "fk_5f9e962a9c24c622",
DROP CONSTRAINT "fk_5f9e962af675f31b",
DROP CONSTRAINT "kf_aa5b128eb36ed395";
ALTER TABLE "public"."comments" ADD CONSTRAINT "fk_reply" FOREIGN KEY ("in_reply_to_id") REFERENCES "public"."comments" ("id") ON UPDATE CASCADE ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_author" FOREIGN KEY ("author_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_content" FOREIGN KEY ("content_id") REFERENCES "public"."contents" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."badge_user_bridges" DROP CONSTRAINT "fk_3b83999e40e556f5",
DROP CONSTRAINT "fk_3b83999ef7a2c2fc",
DROP CONSTRAINT "fk_3b83999ea76ed395",
DROP CONSTRAINT "fk_3b83999e29c1004e";
ALTER TABLE "public"."badge_user_bridges" ADD CONSTRAINT "fk_blueprint" FOREIGN KEY ("blueprint_id") REFERENCES "public"."contents" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_badge" FOREIGN KEY ("badge_id") REFERENCES "public"."badges" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_video" FOREIGN KEY ("video_id") REFERENCES "public"."contents" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."video_views" DROP CONSTRAINT "fk_9e929525a76ed395",
DROP CONSTRAINT "fk_9e92952529c1004e";
ALTER TABLE "public"."video_views" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_video" FOREIGN KEY ("video_id") REFERENCES "public"."contents" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."tokens" DROP CONSTRAINT "fk_aa5a118ea76ed395",
DROP CONSTRAINT "fk_aa5a118ea76ed391";
ALTER TABLE "public"."tokens" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_invite" FOREIGN KEY ("student_invite_id") REFERENCES "public"."student_invites" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."student_invites" DROP CONSTRAINT "fk_ee48df94f624b39d",
DROP CONSTRAINT "fk_ee48df94cb944f1a";
ALTER TABLE "public"."student_invites" ADD CONSTRAINT "fk_sender" FOREIGN KEY ("sender_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_student" FOREIGN KEY ("student_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."paths" DROP CONSTRAINT "fk_8bba8611f675f31b";
ALTER TABLE "public"."paths" ADD CONSTRAINT "fk_author" FOREIGN KEY ("author_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."schemas" DROP CONSTRAINT "fk_9e929223a76ab125";
ALTER TABLE "public"."schemas" ADD CONSTRAINT "fk_author" FOREIGN KEY ("author_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."block_schema_bridges" DROP CONSTRAINT "fk_9e929223a76ed395",
DROP CONSTRAINT "fk_9e929223a76ab123";
ALTER TABLE "public"."block_schema_bridges" ADD CONSTRAINT "fk_schema" FOREIGN KEY ("schema_id") REFERENCES "public"."schemas" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_block" FOREIGN KEY ("block_id") REFERENCES "public"."blocks" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."blocks" DROP CONSTRAINT "fk_9e929223a76ab124";
ALTER TABLE "public"."blocks" ADD CONSTRAINT "fk_author" FOREIGN KEY ("author_id") REFERENCES "public"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "public"."content_block_bridges" DROP CONSTRAINT "fk_aa5b128ea76ed395",
DROP CONSTRAINT "fk_aa6a128ea76ed395";
ALTER TABLE "public"."content_block_bridges" ADD CONSTRAINT "fk_content" FOREIGN KEY ("content_id") REFERENCES "public"."contents" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
ADD CONSTRAINT "fk_block" FOREIGN KEY ("block_id") REFERENCES "public"."blocks" ("id") ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
