CREATE TABLE tokens (
  id SERIAL NOT NULL,
  user_id INT DEFAULT NULL,
  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
  type VARCHAR(255) NOT NULL,
  hash VARCHAR(255) NOT NULL,
  used BOOLEAN NOT NULL,
  PRIMARY KEY(id)
);

CREATE INDEX IDX_AA5A118EA76ED395 ON tokens (user_id);

ALTER TABLE
  tokens
ADD
  CONSTRAINT FK_AA5A118EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
