ALTER TABLE "users"
  ALTER COLUMN "name" DROP NOT NULL,
  ALTER COLUMN "family_name" DROP NOT NULL,
  ALTER COLUMN "nominative" DROP NOT NULL,
  ALTER COLUMN "vocative" DROP NOT NULL,
  ALTER COLUMN "gender" DROP NOT NULL;
